### ISSUE TITLE
Wholesome memes

### ISSUE THREAD

**Issue by chris-y** [fnic-lemmy/lemmy-directory#14]
You have a load of meme communities there, but this one is missing:

wholesome@lemmy.world

**Comment by M4rtineski** [comment]
We already have a community with the same theme from the same instance in the directory. Your suggested community is not only very little active but also has multiple times less subscribers. 
![image](https://github.com/fnic-lemmy/lemmy-directory/assets/137183342/b662bcba-2466-4721-b017-74dd49247a06)

Not sure if it's a good idea to add it. If it was from a different instance then I would be for it because LW is kind of too big but both of those are in the same place.

https://lemmy.world/c/lemmybewholesome

**Comment by chris-y** [comment]
Actually I think it was lemmybewholesome I was thinking of. I didn't see anything like that in the list but must have missed it.
